import type { Metadata } from 'next';
import localFont from 'next/font/local';
import React from 'react';

import 'bootstrap/dist/css/bootstrap.min.css';
import './styles/globals.scss';
import './styles/forms.scss';
import ClientLayoutComponent from '@/shared/ui/components/client-layout.component';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Hexagonal Architecture',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientLayoutComponent />
        {children}
      </body>
    </html>
  );
}
